# Neo4j 5.x 配置
# 服务器内存
server.memory.heap.initial_size=512m
server.memory.heap.max_size=1G
server.memory.pagecache.size=512m

# APOC 插件权限
dbms.security.procedures.unrestricted=apoc.*

# 禁用认证（仅开发/内网使用）
dbms.security.auth_enabled=false

# 网络监听
server.bolt.listen_address=0.0.0.0:7687
server.http.listen_address=0.0.0.0:7474

server.default_listen_address=0.0.0.0
server.directories.logs=/logs
