import { Bot, Download, ExternalLink, Eye, FileText } from "lucide-react";
import type { SearchHit } from "@/services/search";
import { getFileType, isPreviewableSearchHit, sanitizeSearchHighlight } from "./SearchResultList";

interface SearchResultGridProps { hits: SearchHit[]; onView?: (hit: SearchHit) => void; onPreview?: (hit: SearchHit) => void; onOpenOriginal?: (hit: SearchHit) => void; onDownload?: (hit: SearchHit) => void; onAskAI?: (hit: SearchHit) => void; }
export function SearchResultGrid({ hits, onView, onPreview, onOpenOriginal, onDownload, onAskAI }: SearchResultGridProps) { const preview = onPreview ?? onView; return <div className="grid gap-3 bg-white px-4 py-4 sm:px-8 md:grid-cols-2 xl:grid-cols-3">{hits.map((hit) => <article className="flex min-w-0 flex-col rounded border border-slate-200 bg-white p-4 transition hover:border-brand-200 hover:shadow-sm" key={hit.chunkId}><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded bg-brand-600 text-[10px] font-semibold text-white">{getFileType(hit) === "FILE" ? <FileText size={16} /> : getFileType(hit)}</div><div className="min-w-0 flex-1"><h3 className="line-clamp-2 text-sm font-semibold leading-5 text-slate-950">{hit.documentTitle}</h3><p className="mt-1 truncate text-xs text-slate-500">{hit.categoryPath || "未设置路径"}</p></div></div><HighlightedSnippet hit={hit} /><div className="mt-4 flex flex-wrap gap-2 text-xs text-slate-500"><span>{getFileType(hit)}</span><span>·</span><span>{formatDate(hit.updatedAt || hit.createdAt)} 更新</span><span className="rounded bg-slate-100 px-1.5 py-0.5">{permissionLabel(hit.permissionScope)}</span></div><div className="mt-4 flex flex-wrap items-center gap-1 border-t border-slate-100 pt-3">{isPreviewableSearchHit(hit) && <Action label="预览" icon={<Eye size={14} />} onClick={preview ? () => preview(hit) : undefined} primary />}<Action label="打开原文" icon={<ExternalLink size={14} />} onClick={onOpenOriginal ? () => onOpenOriginal(hit) : undefined} />{hit.canDownload !== false && <Action label="下载" icon={<Download size={14} />} onClick={onDownload ? () => onDownload(hit) : undefined} />}{onAskAI && <Action label="向 AI 提问" icon={<Bot size={14} />} onClick={() => onAskAI(hit)} />}</div></article>)}</div>; }
function HighlightedSnippet({ hit }: { hit: SearchHit }) { return hit.highlight?.trim() ? <p className="mt-3 line-clamp-3 min-h-15 text-xs leading-5 text-slate-600" dangerouslySetInnerHTML={{ __html: sanitizeSearchHighlight(hit.highlight) }} /> : <p className="mt-3 line-clamp-3 min-h-15 text-xs leading-5 text-slate-600">{hit.text}</p>; }
function Action({ label, icon, onClick, primary = false }: { label: string; icon: React.ReactNode; onClick?: () => void; primary?: boolean }) { return <button className={`inline-flex min-h-10 items-center gap-1 rounded px-2 text-xs focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 ${primary ? "font-medium text-brand-700 hover:bg-brand-50" : "text-slate-600 hover:bg-slate-50"}`} disabled={!onClick} onClick={onClick} type="button">{icon}{label}</button>; }
function permissionLabel(scope?: string | null) { const map: Record<string, string> = { PRIVATE: "仅本人可见", MEMBERS: "指定成员可见", DEPARTMENTS: "部门可见", COMPANY: "公司可见", PUBLIC: "公开可见", ADMIN: "管理员可见" }; return scope ? map[scope] || scope : "权限范围未知"; }
function formatDate(value?: string | null) { return value ? new Date(value).toLocaleDateString("zh-CN", { year: "numeric", month: "2-digit", day: "2-digit" }) : "未知时间"; }
