import { Download, ExternalLink, Eye, FileText, Sparkles } from "lucide-react";
import type { SearchHit } from "@/services/search";

interface SearchResultListProps { hits: SearchHit[]; onView?: (hit: SearchHit) => void; onPreview?: (hit: SearchHit) => void; onOpenOriginal?: (hit: SearchHit) => void; onDownload?: (hit: SearchHit) => void; onAskAI?: (hit: SearchHit) => void; }
export function SearchResultList({ hits, onView, onPreview, onOpenOriginal, onDownload, onAskAI }: SearchResultListProps) {
  const preview = onPreview ?? onView;
  return <div className="bg-white px-4 sm:px-8">{hits.map((hit) => <article className="flex flex-col gap-3 border-b border-slate-200 py-5 sm:flex-row sm:gap-4" key={hit.chunkId}><FileBadge hit={hit} /><div className="min-w-0 flex-1"><h3 className="text-sm font-semibold leading-5 text-slate-950">{hit.documentTitle}</h3><p className="mt-1 truncate text-xs text-slate-500">{hit.categoryPath || "未设置路径"}</p><HighlightedSnippet className="mt-2 line-clamp-2 text-xs leading-5 text-slate-600" highlight={hit.highlight} text={hit.text} /><ResultMeta hit={hit} /></div><ResultActions hit={hit} onPreview={preview} onOpenOriginal={onOpenOriginal} onDownload={onDownload} onAskAI={onAskAI} /></article>)}</div>;
}
function FileBadge({ hit }: { hit: SearchHit }) { const type = getFileType(hit); return <div aria-label={`文件类型 ${type}`} className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-slate-100 text-[10px] font-semibold text-slate-600 ring-1 ring-inset ring-slate-200">{type === "FILE" ? <FileText size={17} /> : type}</div>; }
function ResultMeta({ hit }: { hit: SearchHit }) { return <div className="mt-3 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-slate-500"><span>{getFileType(hit)}</span><span aria-hidden="true" className="text-slate-300">·</span><span className="tabular">{formatDate(hit.updatedAt || hit.createdAt)} 更新</span><span aria-hidden="true" className="text-slate-300">·</span><span className="rounded bg-slate-100 px-1.5 py-0.5 text-slate-600">{permissionLabel(hit.permissionScope)}</span></div>; }
function ResultActions({ hit, onPreview, onOpenOriginal, onDownload, onAskAI }: { hit: SearchHit; onPreview?: (hit: SearchHit) => void; onOpenOriginal?: (hit: SearchHit) => void; onDownload?: (hit: SearchHit) => void; onAskAI?: (hit: SearchHit) => void }) { return <div className="flex shrink-0 flex-wrap items-center gap-1 sm:self-start">{isPreviewableSearchHit(hit) && <Action label="预览" icon={<Eye size={14} />} onClick={onPreview ? () => onPreview(hit) : undefined} primary />}<Action label="打开原文" icon={<ExternalLink size={14} />} onClick={onOpenOriginal ? () => onOpenOriginal(hit) : undefined} />{hit.canDownload !== false && <Action label="下载" icon={<Download size={14} />} onClick={onDownload ? () => onDownload(hit) : undefined} />}{onAskAI && <Action ai label="向 AI 提问" icon={<Sparkles size={14} />} onClick={() => onAskAI(hit)} />}</div>; }
function Action({ label, icon, onClick, primary = false, ai = false }: { label: string; icon: React.ReactNode; onClick?: () => void; primary?: boolean; ai?: boolean }) { return <button className={`inline-flex min-h-10 items-center gap-1 rounded px-2 text-xs focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 ${ai ? "font-medium text-ai hover:bg-ai-surface/60" : primary ? "font-medium text-brand-700 hover:bg-brand-50" : "text-slate-600 hover:bg-slate-50"}`} disabled={!onClick} onClick={onClick} type="button">{icon}{label}</button>; }
function HighlightedSnippet({ className, highlight, text }: { className: string; highlight?: string | null; text: string }) { return highlight?.trim() ? <p className={className} dangerouslySetInnerHTML={{ __html: sanitizeSearchHighlight(highlight) }} /> : <p className={className}>{text}</p>; }
export function getFileType(hit: SearchHit) { const raw = hit.mime || hit.documentTitle.split(".").pop() || ""; const lower = raw.toLowerCase(); if (lower.includes("pdf")) return "PDF"; if (lower.includes("word") || lower.includes("doc")) return "DOCX"; if (lower.includes("sheet") || lower.includes("excel") || lower.includes("xls")) return "XLSX"; if (lower.includes("presentation") || lower.includes("ppt")) return "PPTX"; if (lower.includes("text") || lower.includes("txt")) return "TXT"; return "FILE"; }
export function isPreviewableSearchHit(hit: SearchHit) { const mime = (hit.mime || "").toLowerCase(); const title = hit.documentTitle.toLowerCase(); return mime === "application/pdf" || mime.includes("markdown") || title.endsWith(".pdf") || title.endsWith(".md") || title.endsWith(".markdown"); }
export function sanitizeSearchHighlight(value: string) { return value.replace(/&(?!(?:amp|lt|gt|quot|#39);)/gi, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/&lt;mark&gt;/gi, "<mark>").replace(/&lt;\/mark&gt;/gi, "</mark>"); }
function permissionLabel(scope?: string | null) { const map: Record<string, string> = { PRIVATE: "仅本人可见", MEMBERS: "指定成员可见", DEPARTMENTS: "部门可见", COMPANY: "公司可见", PUBLIC: "公开可见", ADMIN: "管理员可见" }; return scope ? map[scope] || scope : "权限范围未知"; }
function formatDate(value?: string | null) { return value ? new Date(value).toLocaleDateString("zh-CN", { year: "numeric", month: "2-digit", day: "2-digit" }) : "未知时间"; }
